# Generated by Django 3.0.5 on 2020-04-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_topping_top_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='text',
        ),
    ]
