# Generated by Django 3.0.5 on 2020-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_remove_topping_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='top_choice',
            field=models.CharField(choices=[('B', 'Bacon'), ('S', 'Sausage'), ('P', 'Pepperoni'), ('PN', 'Pineapple'), ('SP', 'Spinach'), ('M', 'Mushrooms'), ('C', 'Chicken'), ('A', 'Anchovies'), ('GP', 'Green Peppers'), ('RP', 'Red Peppers')], max_length=2),
        ),
    ]
